### ISSUE TITLE
Add FriendlyID to project for address slugs

### ISSUE THREAD

**Issue by rsmithlal** [better-together-org/better-together-core#10]
We will want some sort of slug to represent the page of a person, group, etc, so we will use the `FriendlyId` gem. We also want these slugs to be translatable, so we will additionally use the [friendly_id-mobility gem](https://github.com/shioyama/friendly_id-mobility) from shioyama.

### Tasks
- [x] add friendly id gem to gemspec
- [x] require friendly id in engine file
- [x] create `FriendlySlug` module to abstract out common behaviour requirements for friendly slugs
- [x] add specs for module

### Translation Tasks
- [x] add friendly_id-mobility gem to gemspec
- [x] require friendly_id-mobility in engine file
