### ISSUE TITLE
Add Invitable interface

### ISSUE THREAD

**Issue by rsmithlal** [better-together-org/better-together-core#6]
We need to add a new module to contain the behaviour and relationships for invitable classes.

### Tasks
- [ ] Create a new `Inviteable` module
- Instance methods
    - [ ] `invite` - Called on an instance of an invitable record. Takes a person as an argument, with an optional role
    - [ ] `disinvite` - Takes a person as an argument
### Relationships
- [ ] has_many `invitations`
- [ ] has_many `invitees` - through invitations
